package com.bigdoors.domain;

import com.bigdoors.util.BlockPos3;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class DoorAssemblyTest {

    @Test
    void roundTrip_toJsonFromJson_preservesAllFields() {
        DoorAssembly original = new DoorAssembly("test_1", new BlockPos3(1, 2, 3), "north", "hinge");
        original.addHinge(new BlockPos3(1, 3, 3));
        original.addPanel(new BlockPos3(2, 2, 3), 5);
        original.addPanel(new BlockPos3(3, 2, 3), 12);
        original.setDoorSide("left");
        original.setOpen(true);
        original.setOpenDirection("cw");
        original.setPartnerAssemblyId("partner_1");

        JsonObject json = original.toJson();
        DoorAssembly restored = DoorAssembly.fromJson(json);

        assertEquals("test_1", restored.getId());
        assertEquals(new BlockPos3(1, 2, 3), restored.getPrimaryHingePos());
        assertEquals("north", restored.getFacing());
        assertEquals("hinge", restored.getMode());
        assertTrue(restored.isOpen());
        assertEquals("left", restored.getDoorSide());
        assertEquals("cw", restored.getOpenDirection());
        assertEquals("partner_1", restored.getPartnerAssemblyId());
        assertEquals(2, restored.getHingePositions().size());
        assertEquals(2, restored.getPanelPositions().size());
        assertEquals(5, restored.getPanelPositions().get(0).materialIndex());
        assertEquals(12, restored.getPanelPositions().get(1).materialIndex());
    }

    @Test
    void addPanel_increasesPanelCount() {
        DoorAssembly assembly = new DoorAssembly("a", new BlockPos3(0, 0, 0), "north", "hinge");
        assertEquals(0, assembly.getPanelPositions().size());
        assembly.addPanel(new BlockPos3(1, 0, 0), 0);
        assertEquals(1, assembly.getPanelPositions().size());
        assembly.addPanel(new BlockPos3(2, 0, 0), 1);
        assertEquals(2, assembly.getPanelPositions().size());
    }

    @Test
    void removePanel_byCurrentPos_works() {
        DoorAssembly assembly = new DoorAssembly("a", new BlockPos3(0, 0, 0), "north", "hinge");
        assembly.addPanel(new BlockPos3(1, 0, 0), 0);
        // Move panel to a new position
        assembly.updatePanelPositions(List.of(new BlockPos3(0, 0, 1)));
        assertTrue(assembly.removePanel(new BlockPos3(0, 0, 1)));
        assertEquals(0, assembly.getPanelPositions().size());
    }

    @Test
    void removePanel_byClosedPos_works() {
        DoorAssembly assembly = new DoorAssembly("a", new BlockPos3(0, 0, 0), "north", "hinge");
        assembly.addPanel(new BlockPos3(1, 0, 0), 0);
        assembly.updatePanelPositions(List.of(new BlockPos3(0, 0, 1)));
        // Remove by original closedPos
        assertTrue(assembly.removePanel(new BlockPos3(1, 0, 0)));
        assertEquals(0, assembly.getPanelPositions().size());
    }

    @Test
    void removePanel_returnsFalse_forUnknownPosition() {
        DoorAssembly assembly = new DoorAssembly("a", new BlockPos3(0, 0, 0), "north", "hinge");
        assembly.addPanel(new BlockPos3(1, 0, 0), 0);
        assertFalse(assembly.removePanel(new BlockPos3(99, 99, 99)));
    }

    @Test
    void updatePanelPositions_changesCurrentPos() {
        DoorAssembly assembly = new DoorAssembly("a", new BlockPos3(0, 0, 0), "north", "hinge");
        assembly.addPanel(new BlockPos3(1, 0, 0), 0);
        assembly.addPanel(new BlockPos3(2, 0, 0), 1);

        BlockPos3 newPos1 = new BlockPos3(0, 0, 1);
        BlockPos3 newPos2 = new BlockPos3(0, 0, 2);
        assembly.updatePanelPositions(List.of(newPos1, newPos2));

        List<BlockPos3> current = assembly.getAllCurrentPositions();
        assertEquals(newPos1, current.get(0));
        assertEquals(newPos2, current.get(1));
    }

    @Test
    void autoGeneratedIds_areUnique() {
        DoorAssembly a = new DoorAssembly(null, new BlockPos3(0, 0, 0), "north", "hinge");
        DoorAssembly b = new DoorAssembly(null, new BlockPos3(0, 0, 0), "north", "hinge");
        assertNotEquals(a.getId(), b.getId());
    }
}
